apiVersion: v1
kind: Service
metadata:
  name: nginx1-svc
  namespace: nginx-forward
  labels:
    app: nginx1
spec:
  type: ClusterIP
  selector:
    app: nginx1
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
