apiVersion: v1
kind: Service
metadata:
  name: nginx-web-svc
  namespace: nginx-forward
  labels:
    app: nginx-web
spec:
  type: ClusterIP
  selector:
    app: nginx-web
  ports:
  - name: http
    port: 8080
    targetPort: http
    protocol: TCP
