apiVersion: v1
kind: Pod
metadata:
  name: test-client
  namespace: nginx-forward
  labels:
    app: test-client
spec:
  containers:
  - name: test-client
    image: test-client:latest
    imagePullPolicy: IfNotPresent
    command: ["sleep", "infinity"]
